# @package _global_

defaults:
  - override /data: r1pro/eef_torso
  - override /model: vla/g0tiny

model:
  pretrained_ckpt: /TO/Your/Path/G0Tiny_260120

data:
  dataset:
    dataset_dirs: 
      - /TO/Your/Path/Adjust_The_Air_Conditioner_Temperature_20250711_006_v00000000_000000
      - /TO/Your/Path/Arrange_Mineral_Water_Bottles_On_The_Desk_20250721_008_v00000000_000000
