# @package _global_

defaults:
  - override /data: r1lite/arm
  - override /model: vla/pi0

model:
  batch_size: 2

data:
  processor:
    action_output_dim: 32
    proprio_output_dim: 32

    use_stepwise_action_norm: True
    norm_default_mode: "q01/q99"

    action_state_transforms:
      - _target_: galaxea_fm.transforms.relative_action.RelativeJointTransform
        keys: [left_arm, right_arm]

    action_state_merger:
      _target_: galaxea_fm.transforms.action_state_merger.ConcatLeftAlign
      action_target_dim: ${data.processor.action_output_dim}
      state_target_dim: ${data.processor.proprio_output_dim}

  dataset:
    action_size: 50
    dataset_dirs: 
      - /TO/Your/Path/BENCH_Pick_And_Place_20_Items16_Evenly_Distributed_Round_13_20251022_018
      - /TO/Your/Path/BENCH_Pick_And_Place_20_Items57_Evenly_Distributed_Round_13_20251024_018