# @package _global_

defaults:
  - override /data: libero/default
  - override /model: vla/pi0_fast

data:
  dataset:
    action_size: 10

  processor:
    action_output_dim: 32
    proprio_output_dim: 32
    use_stepwise_action_norm: True
    norm_default_mode: "q01/q99"

    action_state_merger:
      _target_: galaxea_fm.transforms.action_state_merger.ConcatLeftAlign
      action_target_dim: ${data.processor.action_output_dim}
      state_target_dim: ${data.processor.proprio_output_dim}

model:
  max_epochs: null
  max_steps: 100000
  warmup_steps: 4000
  tokenizer:
    max_len: 800
  model_arch:
    max_token_len: 256

