pretrained_ckpt: null
use_pretrained_norm_stats: False

# strategy
model_weights_to_bf16: False
enable_bf16_training: False # FIXME
use_torch_compile: False
find_unused_parameters: True # FIXME

# dataloader
batch_size: 4
num_workers: 4
pin_memory: True
persistent_workers: True

# training period
max_epochs: 4
max_steps: null
grad_accumulation_steps: 1

# optimizer
use_8bit_optimizer: False # AdamW8bit or AdamW
learning_rate: 2.5e-5
weight_decay: 1e-6
betas: [0.9, 0.999] # G0

# LR scheduler
lr_scheduler_type: "cosine" # LambdaLR, following openpi
warmup_steps: 1_000

max_grad_norm: 1.0

# EMA
use_ema: False
ema: 
  update_after_step: 0 # Step after which to update EMA weights
  power: 0.67

# sync batch normalization
use_sync_bn: False


tokenizer:
  _target_: galaxea_fm.models.open_pi.paligemma.tokenizer.Pi0Tokenizer
  tokenizer_params:
    max_len: ${model.model_arch.max_text_tokens}
    tokenizer_path: /TO/Your/Path/openpi/big_vision/paligemma_tokenizer.model
  pad_token_id: ${model.model_arch.pad_token_id}
  image_token_index: ${model.model_arch.image_token_index}
  max_text_tokens: ${model.model_arch.max_text_tokens}
  num_tokens_per_image: ${model.model_arch.vision.num_image_tokens}
  num_input_images: ${model.model_arch.num_input_images}


model_arch:
  _target_: galaxea_fm.models.open_pi.pi_policy.PiPolicy
  model_name: galaxea_fm.models.open_pi.pi.Pi

  pretrained_model_path: /TO/Your/Path/openpi/pytorch/pi0_base

  vla_training_strategy: "vla-full-train" # training both vision and language
  backbone_lr_multiplier: 1.0
  image_token_index: 257151
  pad_token_id: 0
  vocab_size: 257152

  cond_steps: ${data.dataset.obs_size}
  horizon_steps: ${data.dataset.action_size}
  max_text_tokens: 200
  num_input_images: ${eval:'${model.model_arch.cond_steps} * ${data.processor.num_output_cameras}'} # $data.window_size * LEN($data.camera_views)
  max_image_text_tokens: ${eval:'${model.model_arch.num_input_images} * ${model.model_arch.vision.num_image_tokens} + ${model.model_arch.max_text_tokens}'}
  final_action_clip_value: null  # data normalized in [-1,1]

  action_dim: 32
  proprio_dim: 32
  action_decoder_layers: 1

  flow_sampling: beta
  num_inference_steps: 10
  time_hidden_size: 1024

  padding_action_weight: 0.0

  vision:
    hidden_size: 1152 # siglip
    intermediate_size: 4304
    num_hidden_layers: 27
    num_attention_heads: 16
    num_channels: 3
    image_size: 224
    patch_size: 14
    hidden_act: gelu_pytorch_tanh
    layer_norm_eps: 0.000001
    attention_dropout: 0.0
    model_type: siglip_vision_model
    projection_dim: 2048
    projector_hidden_act: gelu_fast
    torch_dtype: float32 # TODO bf16
    vision_use_head: false
    vocab_size: ${model.model_arch.vocab_size}

    num_image_tokens: 256

  vision_projector:
    vision_config:
      hidden_size: 1152
      projection_dim: 2048
    
  joint:
    name: galaxea_fm.models.open_pi.joint_model.JointModel
    mixture:
      vlm:   # gemma
        hidden_size: 2048
        intermediate_size: 16384
        use_final_norm: True
        cache: True
        use_adarms: False
      action:
        hidden_size: 1024
        intermediate_size: 4096
        use_final_norm: True
        cache: False
        use_adarms: False  # pi0 doesn't use adaRMS, uses action-time MLP fusion instead

    time_hidden_size: 256 # only applicable if using adaptive
    num_hidden_layers: 18
    num_attention_heads: 8
    num_key_value_heads: 1
    head_dim: 256
    max_position_embeddings: 8192
    rms_norm_eps: 0.000001
    rope_theta: 10000.0

    attention_bias: False
    attention_dropout: 0.0
    bos_token_id: 2
    eos_token_id: 1
    hidden_act: gelu_pytorch_tanh
    hidden_activation: gelu_pytorch_tanh
    initializer_range: 0.02
    model_type: gemma
    torch_dtype: float32 # TODO bf16
    transformers_version: 4.53.2

    pad_token_id: ${model.model_arch.pad_token_id}
    vocab_size: ${model.model_arch.vocab_size}

    use_cache: True

model_meta:
  norm_default_mode: q01/q99 # for proprio tokenization, state must be in [-1, 1]
  input_image_size: 
    - ${model.model_arch.vision.image_size}
    - ${model.model_arch.vision.image_size}